import { makeStyles } from "@material-ui/core";

export const styles = makeStyles({
    chat: {
        height: '100%',
        width: '70%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: '#e6ddd5',
    },
    header: {
        height: 59,
        padding: '10px 16px',
        display: 'flex',
        alignItems: 'center',
        boxSizing: 'border-box',
        backgroundColor: '#ededed',
        borderLeft: '1px solid #00000014',
    },
    contactInfo: {
        display: 'flex',
        flexDirection: 'column',
        flexGrow: 1,
        marginLeft: 15,
        justifyContent: 'center',
        minWidth: 0,
    },
    contactName: {
        display: 'flex',
        flexGrow: 1,
        alignItems: 'flex-start',
        textAlign: 'left',
        overflow: 'hidden',
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '21px',
        whiteSpace: 'nowrap',
        textOverflow: 'ellipsis',
    },
    chatDate: {
        display: 'flex',
        alignItems: 'flex-start',
        minHeight: 20,
        fontSize: '13px',
        lineHeight: '20px',
        color: '#00000099',
    },
    icons: {
        marginLeft: 20,
        display: 'flex',
        flexGrow: 0,
        flexShrink: 0,
        flexBasis: 'auto',
        alignItems: 'center',
    },
    headerIcon: {
        width: 24,
        height: 24,
        padding: '8px',
        marginLeft: '10px',
    },
    attachIcon: {
        transform: 'rotate(45deg)',
    },
    footer: {
        width: '100%',
        minHeight: '62px',
        padding: '5px 10px',
        display: 'flex',
        boxSizing: 'border-box',
        backgroundColor: '#f0f0f0',
    },
    footerIconSmile: {
        width: 48,
        height: 52,
        padding: '5px 10px',
        boxSizing: 'border-box',
    },
    footerIconMic: {
        width: 47,
        height: 52,
        padding: '6px 8px 5px 11px',
        boxSizing: 'border-box',
    },
    input: {
        minHeight: 20,
        margin: '5px 10px',
        padding: '9px 12px 11px',
        border: '1px solid white',
        boxSizing: 'border-box',
        fontSize: 15,
        lineHeight: '20px',
        borderRadius: 21,
        backgroundColor: 'white',
    },
    messageField: {
        flexGrow: 1,
        flexShrink: 1,
    },

    contactImage : {
        width: 40,
        height: 40,
        borderRadius: 50,
    },
})